version: '1.0.{build}'

skip_tags: true

build_script:
- echo Version %APPVEYOR_BUILD_VERSION%
- npm install -g grunt-cli
- npm install
- grunt production

artifacts:
- path: validation-wrapper
  name: validation-wrapper

deploy:
- provider: GitHub
  artifact: /.*\.zip/
  auth_token:
    secure: HiCVoH9XLPbrdI9Qyfc+OzttDUYrvfGHQv1lw2yEZTX/N/cbAbvzKmzUoE9pUhJ x
  on:
    branch: master