version: '1.0.{build}'

build_script:
- cd validation-wrapper
- npm install -g grunt-cli
- npm install
- grunt production

artifacts:
- path: validation-wrapper\production
  name: validation-wrapper

deploy:
- provider: GitHub
  artifact: validation-wrapper.zip