version: '1.0.{build}'

build_script:
- cd validation-wrapper
- npm install -g grunt-cli
- npm install
- grunt production
- dir
- cd production
- dir

artifacts:
- path: production/*
  name: validation-wrapper.zip