version: '1.0.{build}'

skip_tags: true

skip_commits:
  message: "**no_build**"

build_script:
- echo Version %APPVEYOR_BUILD_VERSION%
- npm install -g grunt-cli
- npm install
- grunt production

artifacts:
- path: dist
  name: validation-wrapper

deploy:
- provider: GitHub
  artifact: /.*\.zip/
  auth_token:
    secure: HiCVoH9XLPbrdI9Qyfc+OzttDUYrvfGHQv1lw2yEZTX/N/cbAbvzKmzUoE9pUhJ x
  on:
    branch: master

environment:
  access_token:
    secure: HiCVoH9XLPbrdI9Qyfc+OzttDUYrvfGHQv1lw2yEZTX/N/cbAbvzKmzUoE9pUhJ x

on_success:
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.email jamesfaceface@live.co.uk
- git config --global user.name jamesfaceface
- git pull %APPVEYOR_REPO_BRANCH%
- git add dist/*.*
- git commit -m "**no_build** assets committed"
- git push 